meson:Update meson version to 0.58.0 and more
This is required in order to use meson dep.get_variable() with
positional argument.

Below is the error encountered with a meson version lesser than 0.58.

Exception: dep.get_variable() with positional argument requires
meson_Version: '>=0.58'

Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>